/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign9;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClickSubtypeStatisticsKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClickSubtypeStatisticsKey\",\"namespace\":\"com.refactorlabs.cs378.assign9\",\"fields\":[{\"name\":\"session_type\",\"type\":\"string\",\"default\":\"any\"},{\"name\":\"click_subtype\",\"type\":\"string\",\"default\":\"any\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence session_type;
  @Deprecated public java.lang.CharSequence click_subtype;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ClickSubtypeStatisticsKey() {}

  /**
   * All-args constructor.
   */
  public ClickSubtypeStatisticsKey(java.lang.CharSequence session_type, java.lang.CharSequence click_subtype) {
    this.session_type = session_type;
    this.click_subtype = click_subtype;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return session_type;
    case 1: return click_subtype;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: session_type = (java.lang.CharSequence)value$; break;
    case 1: click_subtype = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'session_type' field.
   */
  public java.lang.CharSequence getSessionType() {
    return session_type;
  }

  /**
   * Sets the value of the 'session_type' field.
   * @param value the value to set.
   */
  public void setSessionType(java.lang.CharSequence value) {
    this.session_type = value;
  }

  /**
   * Gets the value of the 'click_subtype' field.
   */
  public java.lang.CharSequence getClickSubtype() {
    return click_subtype;
  }

  /**
   * Sets the value of the 'click_subtype' field.
   * @param value the value to set.
   */
  public void setClickSubtype(java.lang.CharSequence value) {
    this.click_subtype = value;
  }

  /** Creates a new ClickSubtypeStatisticsKey RecordBuilder */
  public static com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder newBuilder() {
    return new com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder();
  }
  
  /** Creates a new ClickSubtypeStatisticsKey RecordBuilder by copying an existing Builder */
  public static com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder newBuilder(com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder other) {
    return new com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder(other);
  }
  
  /** Creates a new ClickSubtypeStatisticsKey RecordBuilder by copying an existing ClickSubtypeStatisticsKey instance */
  public static com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder newBuilder(com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey other) {
    return new com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder(other);
  }
  
  /**
   * RecordBuilder for ClickSubtypeStatisticsKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClickSubtypeStatisticsKey>
    implements org.apache.avro.data.RecordBuilder<ClickSubtypeStatisticsKey> {

    private java.lang.CharSequence session_type;
    private java.lang.CharSequence click_subtype;

    /** Creates a new Builder */
    private Builder() {
      super(com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.session_type)) {
        this.session_type = data().deepCopy(fields()[0].schema(), other.session_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.click_subtype)) {
        this.click_subtype = data().deepCopy(fields()[1].schema(), other.click_subtype);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ClickSubtypeStatisticsKey instance */
    private Builder(com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey other) {
            super(com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.SCHEMA$);
      if (isValidValue(fields()[0], other.session_type)) {
        this.session_type = data().deepCopy(fields()[0].schema(), other.session_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.click_subtype)) {
        this.click_subtype = data().deepCopy(fields()[1].schema(), other.click_subtype);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'session_type' field */
    public java.lang.CharSequence getSessionType() {
      return session_type;
    }
    
    /** Sets the value of the 'session_type' field */
    public com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder setSessionType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.session_type = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'session_type' field has been set */
    public boolean hasSessionType() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'session_type' field */
    public com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder clearSessionType() {
      session_type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'click_subtype' field */
    public java.lang.CharSequence getClickSubtype() {
      return click_subtype;
    }
    
    /** Sets the value of the 'click_subtype' field */
    public com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder setClickSubtype(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.click_subtype = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'click_subtype' field has been set */
    public boolean hasClickSubtype() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'click_subtype' field */
    public com.refactorlabs.cs378.assign9.ClickSubtypeStatisticsKey.Builder clearClickSubtype() {
      click_subtype = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ClickSubtypeStatisticsKey build() {
      try {
        ClickSubtypeStatisticsKey record = new ClickSubtypeStatisticsKey();
        record.session_type = fieldSetFlags()[0] ? this.session_type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.click_subtype = fieldSetFlags()[1] ? this.click_subtype : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
