/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.assign7;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BodyStyle { 
  Coupe, Hatchback, Minivan, Pickup, SUV, Sedan  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BodyStyle\",\"namespace\":\"com.refactorlabs.cs378.assign7\",\"symbols\":[\"Coupe\",\"Hatchback\",\"Minivan\",\"Pickup\",\"SUV\",\"Sedan\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
