/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.refactorlabs.cs378.sessions;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventSubtype { 
  CONTACT_FORM_TYPE, ALTERNATIVE, CONTACT_BANNER, CONTACT_BUTTON, DEALER_PHONE, FEATURES_SECTION, GET_DIRECTIONS, VEHICLE_HISTORY, ERROR, SUCCESS, ALTERNATIVES, ILMR_REPORT_LISTING, CONTACT_FORM, LOAD_ERROR, FINANCING, INSPECTION, ROADSIDE, SIRIUS, WARRANTY, SEE_MORE, ILMR_VIDEO, ILMR, BADGE_DETAIL, PHOTO_MODAL, BADGES, FEATURES, MARKET_REPORT_LISTING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventSubtype\",\"namespace\":\"com.refactorlabs.cs378.sessions\",\"symbols\":[\"CONTACT_FORM_TYPE\",\"ALTERNATIVE\",\"CONTACT_BANNER\",\"CONTACT_BUTTON\",\"DEALER_PHONE\",\"FEATURES_SECTION\",\"GET_DIRECTIONS\",\"VEHICLE_HISTORY\",\"ERROR\",\"SUCCESS\",\"ALTERNATIVES\",\"ILMR_REPORT_LISTING\",\"CONTACT_FORM\",\"LOAD_ERROR\",\"FINANCING\",\"INSPECTION\",\"ROADSIDE\",\"SIRIUS\",\"WARRANTY\",\"SEE_MORE\",\"ILMR_VIDEO\",\"ILMR\",\"BADGE_DETAIL\",\"PHOTO_MODAL\",\"BADGES\",\"FEATURES\",\"MARKET_REPORT_LISTING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
